### ISSUE TITLE
Which datasets the models were pre-trained on?

### ISSUE THREAD

**Issue by wyalves** [serengil/deepface_models#5]
First of all, thank you for the great job you are doing. This lib is amazing and it's helping me a lot with my BSc thesis (and I'll be referencing it appropriately).

However, there is an essential piece of information that I couldn't find anywhere, not even in your blog posts (_maybe I didn't search properly_): Which datasets were the models pre-trained on?

I saw that someone asked the same question on issue #2, but I don't think it was actually answered.

**Comment by serengil** [comment]
I used pre-trained models. You can find the original researches in the license section. Reference datasets were mentioned in those researches.
