### ISSUE TITLE
YOLO Model for Release

### ISSUE THREAD

**Issue by sbmalik** [serengil/deepface_models#7]
Please add this model to next release so the YOLO model's path can be updated in deepface. 
Referring to this issue https://github.com/serengil/deepface/issues/939

[yolov8n_face.pt.zip](https://github.com/serengil/deepface_models/files/13799121/yolov8n_face.pt.zip)

**Comment by serengil** [comment]
I am just uploading h5 files that I exported to that repo. Uploading this file may cause copyright issue. Instead, I prefer to download it from external repo.

For instance, [this repo](https://github.com/akanametov/yolov8-face) publishes that weight file in the url: https://github.com/akanametov/yolov8-face/releases/download/v0.0.0/yolov8n-face.pt
